services:
  web:
    image: php:8.3.21-apache
    container_name: blog_apache
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: blog_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogdb
      MYSQL_USER: julian
      MYSQL_PASSWORD: julianpassword
    #command: --init-file /data/application/init.sql
    volumes:
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data: